<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net48</TargetFramework>
    <LangVersion>latest</LangVersion>
    <UseWPF>true</UseWPF>
    <Nullable>enable</Nullable>
    <AssemblyName>YMacType.Settings</AssemblyName>
    <RootNamespace>YMacType.Settings</RootNamespace>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <Version>1.2026.730.3</Version>
    <FileVersion>1.2026.730.3</FileVersion>
    <AssemblyVersion>1.2026.730.3</AssemblyVersion>
  </PropertyGroup>
  <ItemGroup>
    <Reference Include="Microsoft.CSharp" />
    <Reference Include="System.Drawing" />
    <Reference Include="System.Windows.Forms" />
  </ItemGroup>
</Project>
